import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";

export default function Layout({ children }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container mx-auto px-4 min-h-screen flex justify-between flex-col">
				<Header />
				<main className="h-full mb-16">{children}</main>
				<Footer />
			</div>
		</>
	);
}
