import Head from "next/head";
import { IoPersonCircle } from "react-icons/io5";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Home from ".";
import error from "next/error";
import Layout from "../components/Layout";

export default function Main() {
	const session = useSession();
	const supabase = useSupabaseClient();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col items-center">
				<>
					{!session ? (
						<>
							<Auth
								supabaseClient={supabase}
								appearance={{ theme: ThemeSupa }}
								theme="dark"
							/>
						</>
					) : (
						<Home session={session} />
					)}
				</>
			</main>
		</>
	);
}
